name: Build Pipeline

on:
  push:
    branches:
      - split-steps

  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.8"

      - name: Assemble JAR
        run: gradle --build-cache assemble

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: worker-jar
          path: build/libs/*.jar
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: worker-jar
          path: build/libs

      - name: LS
        run: | 
          ls -al
          cd build/libs
          pwd
          ls -al
          cd ../..

      - name: Build Docker image of application
        run: docker build -t bp3global/c7-rest-worker .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "bp3docker"
          password: ${{ secrets.DOCKERHUB_BP3DOCKER }}

      - name: Push Docker image to Docker Hub
        run: docker push bp3global/c7-rest-worker
