name: Build Pipeline

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image of application
        run: docker build -t bp3global/c7-rest-worker .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "bp3docker"
          password: ${{ secrets.DOCKERHUB_BP3DOCKER }}

      - name: Push Docker image to Docker Hub
        run: docker push bp3global/c7-rest-worker
